### ISSUE TITLE
Browse Groups tricks me every time

### ISSUE THREAD

**Issue by jxjj** [UMN-LATIS/bluesheet#12]
Small nit: on the [Browse Groups page](https://bluesheet.cla.umn.edu/groups) to me the Groups breadcrumb heading reads as an input element with "Groups" as placeholder text. And the Search input reads as a button:

![CleanShot 2022-10-05 at 15 29 44@2x](https://user-images.githubusercontent.com/980170/194158083-e0e65616-3d77-44a1-8e56-f02e8aec7f5b.png)

I usually click a few times before my brain engages and realizes what's going on...

Maybe moving the search input to its own line to give it more space for input?

**Comment by cmcfadden** [comment]
that makes sense. I think I probably made it worse when we switched up the header.
