### ISSUE TITLE
Group action buttons not rendering correctly 

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/bluesheet#14]
dev:
![Screenshot 2023-07-14 at 10 59 23 AM](https://github.com/UMN-LATIS/bluesheet/assets/211655/87e49720-8c3e-4b72-ba5c-9951782415dc)

prod:
![Screenshot 2023-07-14 at 10 59 34 AM](https://github.com/UMN-LATIS/bluesheet/assets/211655/f6a7cd5c-adc0-4a09-b375-a91a44e366e7)

**Comment by jxjj** [comment]
Update on dev:
<img width="500" alt="ScreenShot 2023-07-18 at 20 15 06@2x" src="https://github.com/UMN-LATIS/bluesheet/assets/980170/bef684e2-ebee-4bea-952c-1f85196fd24d">
