### ISSUE TITLE
Navbar items not justified on dev

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/bluesheet#17]
DeV:
![Screenshot 2023-07-14 at 11 01 01 AM](https://github.com/UMN-LATIS/bluesheet/assets/211655/e2945821-f1e4-4f95-8c59-b478eef28a8a)

Prod:
![Screenshot 2023-07-14 at 11 01 11 AM](https://github.com/UMN-LATIS/bluesheet/assets/211655/0652b00f-a3a7-4c43-9c72-20dfbceff53c)

**Comment by jxjj** [comment]
Updated on dev:
<img width="500" alt="ScreenShot 2023-07-18 at 20 18 48@2x" src="https://github.com/UMN-LATIS/bluesheet/assets/980170/7d4ddccd-8ac7-47aa-9dd2-0de583d584aa">
