### ISSUE TITLE
Margins off on groups items

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/bluesheet#18]
dev:
![Screenshot 2023-07-14 at 11 01 30 AM](https://github.com/UMN-LATIS/bluesheet/assets/211655/68715c32-2d7d-4e0f-b705-036de5b56bb0)

Prod:
![Screenshot 2023-07-14 at 11 01 39 AM](https://github.com/UMN-LATIS/bluesheet/assets/211655/6be99a28-801e-43ec-8ba8-114b6e40922e)

**Comment by jxjj** [comment]
Updated on dev:
<img width="340" alt="ScreenShot 2023-07-18 at 20 19 42@2x" src="https://github.com/UMN-LATIS/bluesheet/assets/980170/ff00598e-b343-43c8-b065-e36af542f4c4">
