### ISSUE TITLE
LeaveTableRow swaps keys/values?

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/bluesheet#185]
Was looking into #184 and noticed that this function seems to swap the key and the value from LeaveStatuses. IE, I updated:

```
export const leaveStatuses = {
  CONFIRMED: "confirmed",
  PENDING: "pending",
  ELIGIBLE: "eligible",
  CANCELLED: "deferred",
} as const;
```

and when editing a leave, the dropdown label is "cancelled" but the value is "deferred". Is that intentional? 

https://github.com/UMN-LATIS/bluesheet/blob/0fca5dff87e00147440a2cf6e35543658ca50a5d/resources/js/components/LeavesTable/LeaveTableRow.vue#L227-L232

**Comment by jxjj** [comment]
`leaveStatuses` is a mapping from a constant to the value stored in the database, not a mapping to a text label.  Basically an enum. I can see how it's kinda confusing – maybe there's a better variable name, or better to structure the Leave Status with both the db string and the human label.

Obviated by #184
