### ISSUE TITLE
Last modified report showing invalid dates

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/bluesheet#19]
https://cla-groups-dev.oit.umn.edu/reports/lastModified

**Comment by jxjj** [comment]
Caused by undefined dates.
Updated on dev:
<img width="688" alt="ScreenShot 2023-07-18 at 20 20 29@2x" src="https://github.com/UMN-LATIS/bluesheet/assets/980170/ceb8d267-5234-4e91-b6c7-287b873aec99">
