### ISSUE TITLE
select dropdown rendering controls wrong

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/bluesheet#20]
![Screenshot 2023-07-14 at 11 03 29 AM](https://github.com/UMN-LATIS/bluesheet/assets/211655/40ebd2a7-2ae3-4bad-851b-68f713313407)

(seems to be doing this on all of the vue-selects)

**Comment by jxjj** [comment]
Fixed on dev when switching from vue-select to a ComboBox component:
<img width="296" alt="ScreenShot 2023-07-18 at 20 23 20@2x" src="https://github.com/UMN-LATIS/bluesheet/assets/980170/96a07588-fa40-4167-98bd-e7d939e66bb4">

There may be different issues that emerge with the custom ComboBox.
