### ISSUE TITLE
Adding members broken

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/bluesheet#201]
Z-index is wrong on the role popup so new members can't be added. 

For the moment, I monkey patched it on dev and redeployed (with a z-index:10000 on that dropdown) so that an admin could get back up and running. Issue seems to be the change for leaves around teleporting the combobox, which loses the 9998 zindex of the modal. 

<img width="1582" alt="Screenshot 2024-09-10 at 9 54 32 AM" src="https://github.com/user-attachments/assets/9345060e-532c-46e9-9d7e-e7a9670908b0">

**Comment by jxjj** [comment]
fixed with https://github.com/UMN-LATIS/bluesheet/commit/5a6da50f50afea198219c11fe04747a00dc0ddb0

🙏 @cmcfadden
