### ISSUE TITLE
course planning mode combobox selection very slow to open in History group

### ISSUE THREAD

**Issue by jxjj** [UMN-LATIS/bluesheet#212]
Open takes ~8s in the video below.

Maybe because we're creating a combobox with ALL courses that faculty have ever taught rather than just departmental courses?

https://github.com/user-attachments/assets/84a9b048-0794-42d1-9fe3-dc9ed15650ee

**Comment by cmcfadden** [comment]
I think we could safely limit it to just the department in question if it helps perf meaningfully.

-Colin

**Comment by jxjj** [comment]
Thanks. I have to confirm that it's the issue. There may also be a virtual scroller thing that we can use.
