### ISSUE TITLE
Child groups rendering wrong in Vue3

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/bluesheet#29]
Vue3 (on dev):

<img width="344" alt="Screenshot 2023-07-27 at 1 01 53 PM" src="https://github.com/UMN-LATIS/bluesheet/assets/211655/f01a6361-1916-41f6-8647-da75dff56f0b">

Prod:
<img width="588" alt="Screenshot 2023-07-27 at 1 02 26 PM" src="https://github.com/UMN-LATIS/bluesheet/assets/211655/a4fa3ef1-8600-4ced-b7f7-e16b8e2bdd89">

**Comment by jxjj** [comment]
Closed by #37
