### ISSUE TITLE
Scheduling Report: Rename to "Faculty Leaves Planning Report"

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/bluesheet#91]
Admins expressed concern that "Scheduling Report" implies that it changes peoplesoft schedule.

**Comment by jxjj** [comment]
"Course Planning" could be another option if there' another Leaves report.

**Comment by cmcfadden** [comment]
Faculty Leaves Planning View or something would work, but I think the request was specifically to keep it focused on faculty leaves
