### ISSUE TITLE
Fiscal Report page refers to non-existant "show email list" button

### ISSUE THREAD

**Issue by jxjj** [UMN-LATIS/bluesheet#99]
The top of the [Fiscal Report page](https://bluesheet.cla.umn.edu/reports/fiscal) refers to a button that isn't present anymore.

![ScreenShot 2024-01-31 at 11 10 57@2x](https://github.com/UMN-LATIS/bluesheet/assets/980170/7b8b3ad8-d034-46a5-84b0-a3d987dbc941)

**Comment by cmcfadden** [comment]
Pretty sure the button was never there - we can just remove that text.
